version: ~> 1.0
language: java

env:
  global:
    - M2_CACHE_CLEAN_DIR: "org/simplify4u/jfatek/"
    - SONAR_ORG: "simplify4u"
    - MY_REPO: "s4u/jfatek"

import:
  - source: s4u/travis:install.yml@master
  - source: s4u/travis:m2-cache.yml@master
  - source: s4u/travis:standard-jobs.yml@master
  - source: s4u/travis:deploy-ghpages.yml@master

